
# index of coil to command string
coil_to_command_lookup = {
   1: "timeseries",
   2: "eis_settings",
   3: "ocv",
   4: "eis", 
   5: "eis_done",
   6: "file_logging_settings",
   7: "clear_eis_frequency_list",
   8: "set_eis_frequency_list",
   9: "get_eis_settings",
   10: "query_fpga_primary_info",
   11: "query_fpga_secondary_info",
   12: "query_fpga_status",
   13: "get_file_logging_settings",
   14: "get_fpga_settings",
   15: "get_eis_settings",
   16: "set_operator",
   17: "set_project",
   18: "set_eis_filename",
   19: "set_eis_title",
   20: "set_eis_tag",
   21: "set_eis_notes",
   22: "clear_eis_settings",
   23: "set_eis_start_frequency",
   24: "set_eis_points_per_decade",
   25: "update_frequency_list",
   26: "clear_eis_frequency_list",
   27: "set_eis_ocv_ms",
   28: "set_eis_periods",
   29: "start_eis_test",
   30: "stop_eis_test",
   31: "reset_eis_test",
   32: "set_auto_eis",
   33: "set_i_zero",
   34: "set_i_dir",
   35: "set_i_ripple",
   36: "set_ocp_limit",
   37: "set_blank_count",
   38: "set_dead_pk",
   39: "set_daed_vly",
   40: "set_pwr_switch",
   41: "set_flt_switch",
   42: "set_freq_switch",
   43: "set_sine_switch",
   44: "set_bid",
   45: "index",
   46: "current",
   47: "voltage",
}


# command string to index of coil 
command_to_coil_lookup = {
   "timeseries": 1,
   "eis_settings": 2,
   "ocv": 3,
   "eis": 4,
   "eis_done": 5,
   "file_logging_settings": 6,
   "clear_eis_frequency_list": 7,
   "set_eis_frequency_list": 8,
   "get_eis_settings": 9,
   "query_fpga_primary_info": 10,
   "query_fpga_secondary_info": 11,
   "query_fpga_status": 12,
   "get_file_logging_settings": 13,
   "get_fpga_settings": 14,
   "get_eis_settings": 15,
   "set_operator": 16,
   "set_project": 17,
   "set_eis_filename": 18,
   "set_eis_title": 19,
   "set_eis_tag": 20,
   "set_eis_notes": 21,
   "clear_eis_settings": 22,
   "set_eis_start_frequency": 23,
   "set_eis_points_per_decade": 24,
   "update_frequency_list": 25,
   "clear_eis_frequency_list": 26,
   "set_eis_ocv_ms": 27,
   "set_eis_periods": 28,
   "start_eis_test": 29,
   "stop_eis_test": 30,
   "reset_eis_test": 31,
   "set_auto_eis": 32,
   "set_i_zero": 33,
   "set_i_dir": 34,
   "set_i_ripple": 35,
   "set_ocp_limit": 36,
   "set_blank_count": 37,
   "set_dead_pk": 38,
   "set_daed_vly": 39,
   "set_pwr_switch": 40,
   "set_flt_switch": 41,
   "set_freq_switch": 42,
   "set_sine_switch": 43,
   "set_bid": 44,
   "index": 45,
   "current": 46,
   "voltage": 47,
}

# Point to first address of each dataset
command_to_register_lookup = {
   "timeseries": 0,
   "eis_settings": 58,
   "ocv": 3512,                        # Address of number of ocv entries (uint32).  Actual entries follow 
   "eis": 1312,                        # Address of number of eis entries (uint32).  Actual entries follow 
   "eis_done": 321, 
   "file_logging_settings": 579, 
   "set_operator": 879,
   "set_project": 929,
   "set_eis_filename": 979,
   "set_eis_title": 1029,
   "set_eis_tag": 1079,
   "set_eis_notes": 1129,
   "set_eis_start_frequency": 1179,
   "set_eis_end_frequency": 1183,
   "set_eis_points_per_decade": 1187,
   "clear_eis_frequency_list": 1191,
   "set_eis_ocv_ms": 1241,
   "set_eis_sample_ms": 1243,
   "set_eis_periods": 1245,
   "set_i_zero": 1246,
   "set_i_dir": 1248,
   "set_i_ripple": 1250,
   "set_i_dcdc": 1252,
   "set_ocp_limit": 1254,
   "set_blank_count": 1256,
   "set_dead_pk": 1258,
   "set_dead_vly": 1260,
   "set_bid": 1262,
}

# data type stored at each address
command_to_type_lookup = {
   "timeseries": "dict",
   "eis_settings": "dict",
   "ocv": "uint32",                        # Address of number of ocv entries (uint32).  Actual entries follow 
   "eis": "uint32",                        # Address of number of eis entries (uint32).  Actual entries follow 
   "eis_done": "dict", 
   "file_logging_settings": "dict", 
   "set_operator": "str",
   "set_project": "str",
   "set_eis_filename": "str",
   "set_eis_title": "str",
   "set_eis_tag": "str",
   "set_eis_notes": "str",
   "set_eis_start_frequency": "double",
   "set_eis_end_frequency": "double",
   "set_eis_points_per_decade": "double",
   "clear_eis_frequency_list": "str",
   "set_eis_ocv_ms": "uint32",
   "set_eis_sample_ms": "uint32",
   "set_eis_periods": "uint8",
   "set_i_zero": "uint32",
   "set_i_dir": "uint32",
   "set_i_ripple": "uint32",
   "set_i_dcdc": "uint32",
   "set_ocp_limit": "uint32",
   "set_blank_count": "uint32",
   "set_dead_ph": "uint32",
   "set_dead_vly": "uint32",
   "set_bid": "str",
}

modbus_type_sizes = {
   "str": 50,
   "double": 4,
   "float": 2,
   "uint64": 4,
   "uint32": 2,
   "uint16": 1,
   "uint8": 1,
}